# C:\scripts\my_app\my_erp_project\backend\erp_config\EMS\urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EmployeeViewSet # Import your viewset

# Create a router and register our viewsets with it.
# DefaultRouter automatically creates the URL patterns for standard actions (list, create, retrieve, etc.)
router = DefaultRouter()
router.register(r'employees', EmployeeViewSet, basename='employee')
# router.register(r'other_models', OtherViewSet) # You can register other viewsets here later

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)), # Include the URLs generated by the router
]