# Generated by Django 5.2 on 2025-04-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_emergencycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
